### PR TITLE
Include building of mpg123 to feature mp3 playing on emulators

### PR DESCRIPTION
**Pull request by TheRealMoeder**

### CODE REVIEW

**Review by F-D-R — CHANGES_REQUESTED** [review]
Would you replace the tabs with spaces?

**Review by F-D-R — CHANGES_REQUESTED** [review]
There are six more...  :)

**Comment by TheRealMoeder** [comment]
I have not cloned this repo...would you mind telling me where they are? I cannot see them in the github editor :(
Or just merge and quickly fix them yourself...

**Comment by TheRealMoeder** [comment]
Found 'em...although I'm pretty sure they have been there before ;)

**Review by F-D-R — APPROVED** [review]

**Pull request merged**
